# _config.yml

# Основные настройки Jekyll
title: My Jekyll Site
description: This is a test site
baseurl: "" # Укажите, если нужно
url: "https://username.github.io" # Укажите ваш URL

# Exclude — исключает файлы и папки из сборки
exclude:
  - */node_modules
  - */.jekyllignore

# Плагины
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Настройки пагинации
paginate: 10
paginate_path: "/page:num/"
